### ISSUE TITLE
[Bug] Add warning before downloading project files

### ISSUE THREAD

**Issue by ahaim5357** [ahaim5357/project-patcher#18]
Currently, no warning is given before downloading project files. This should be remedied on a per-project basis stored in a `.prjmn` file. This file will be formatted as a TOML file and hold project related settings. Additionally, the user can disable this completely.

```toml
[project]

# When true, shows a warning message relating to downloading a project file.
display_warning_message = true
```
